export const SET_X_PLAYER = 'SET_X_PLAYER';
export const SET_O_PLAYER = 'SET_O_PLAYER';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_WINNER = 'SET_WINNER';
export const SET_STATUS_MATCH = 'SET_STATUS_MATCH';
export const SET_BOARD_STATES = 'SET_BOARD_STATES';
export const SET_CURRENT_BOARD_STATE = 'SET_CURRENT_BOARD_STATE';
export const SET_RESULT = 'SET_RESULT';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const CHECK_AUTHORIZATED_SUCCESS = 'CHECK_AUTHORIZATED_SUCCESS';
export const CHECK_AUTHORIZATED_FAILED = 'CHECK_AUTHORIZATED_FAILED';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';

export const PROCESS_SOMETHING = 'PROCESS_SOMETHING';
export const DONE_PROCESS_SOMETHING = 'DONE_PROCESS_SOMETHING';
